name: Test build

on:
  push:
    branches:
      - main
      - Dev

jobs:
  test-build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      PORT: 25277
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - run: cd .\app\
      - name: 'Install Node'
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: yarn install 
      - name: "Run Test"
        run: yarn test
      - name: "Build"
        run: yarn build