name: Test build

on:
  push:
    branches:
      - main
      - Dev

jobs:
  test-build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      PORT: 25277
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Node'
        uses: actions/setup-node@v2
      - name: "Install dependencies"
        run: |
          cd .\app\
          yarn install 
      - name: "Run Test"
        run: |
          cd .\app\
          yarn test
      - name: "Build"
        run: |
          cd .\app\
          yarn build